version: '3'

services:
  docker-redis:
    image: redis
    hostname: redis
    ports:
      - '6379:6379'
    expose:
      - 6379
    networks:
      - host

  docker-mysql:
    image: mysql:${mysql_version}
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
      - MYSQL_DATABASE=${mysql_database}
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_password}
    ports:
      - "3307:3306"
    expose:
      - 3306
    networks:
      - host

  app:
    image: project-tracking-img:latest
    ports:
       - "3000:3000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/bug_tracking?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${mysql_user}
      SPRING_DATASOURCE_PASSWORD: ${mysql_password}
      SERVER_PORT: 3000
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
      SPRING_JPA_SHOW-SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      JWTP_SECRETKEY: ">[)?&NGT}._c+Y?K67mQxyL4Tfk2S,8jh|3dqC&l-po=$$?x.BB:/!SXW+*1o?`NUA@)]Ybz%xevPvhj;pGI.Z8>xD?%06+gq]*6:1G[.`Xxbkf[*NsKDyaICVJ=?4)"
      SPRING_CACHE_TYPE: redis
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - host
    depends_on:
       - docker-mysql
       - docker-redis
networks:
  host: