version: '3'

services:
  docker-mysql:
    image: mysql:${mysql_version}
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
      - MYSQL_DATABASE=${mysql_database}
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_password}
    ports:
      - "3307:3306"
    expose:
      - 3306
    networks:
      - host

  app:
    image: project-tracking-img:latest
    ports:
       - "3000:3000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/bug_tracking?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${mysql_user}
      SPRING_DATASOURCE_PASSWORD: ${mysql_password}
      SERVER_PORT: 3000
    networks:
      - host
    depends_on:
       - docker-mysql
networks:
  host: